[package]
name = "pml"
version = "0.5.2"
edition = "2021"
license = "Apache-2.0"
description = "A parser for PML, just another format to specify your configs in"
repository = "https://github.com/PhilVoel/pml.rs"
readme = "README.md"
categories = ["config", "parsing"]

[dependencies]
